/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatercoolerRouteImport } from './routes/watercooler'
import { Route as VacationRouteImport } from './routes/vacation'
import { Route as SubmitStoryRouteImport } from './routes/submit-story'
import { Route as StoryDraftsRouteImport } from './routes/story-drafts'
import { Route as SnakeRouteImport } from './routes/snake'
import { Route as SmasherRouteImport } from './routes/smasher'
import { Route as ShredderRouteImport } from './routes/shredder'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as MyBreakroomRouteImport } from './routes/my-breakroom'
import { Route as MelodyRouteImport } from './routes/melody'
import { Route as MatchRouteImport } from './routes/match'
import { Route as CommunityStoriesRouteImport } from './routes/community-stories'
import { Route as BubblesRouteImport } from './routes/bubbles'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BingoRouteImport } from './routes/bingo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminWatercoolerRouteImport } from './routes/admin-watercooler'
import { Route as AdminSubmissionsRouteImport } from './routes/admin-submissions'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R2048RouteImport } from './routes/2048'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WatercoolerRoute = WatercoolerRouteImport.update({
  id: '/watercooler',
  path: '/watercooler',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationRoute = VacationRouteImport.update({
  id: '/vacation',
  path: '/vacation',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitStoryRoute = SubmitStoryRouteImport.update({
  id: '/submit-story',
  path: '/submit-story',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryDraftsRoute = StoryDraftsRouteImport.update({
  id: '/story-drafts',
  path: '/story-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakeRoute = SnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const SmasherRoute = SmasherRouteImport.update({
  id: '/smasher',
  path: '/smasher',
  getParentRoute: () => rootRouteImport,
} as any)
const ShredderRoute = ShredderRouteImport.update({
  id: '/shredder',
  path: '/shredder',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBreakroomRoute = MyBreakroomRouteImport.update({
  id: '/my-breakroom',
  path: '/my-breakroom',
  getParentRoute: () => rootRouteImport,
} as any)
const MelodyRoute = MelodyRouteImport.update({
  id: '/melody',
  path: '/melody',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStoriesRoute = CommunityStoriesRouteImport.update({
  id: '/community-stories',
  path: '/community-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const BubblesRoute = BubblesRouteImport.update({
  id: '/bubbles',
  path: '/bubbles',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoRoute = BingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWatercoolerRoute = AdminWatercoolerRouteImport.update({
  id: '/admin-watercooler',
  path: '/admin-watercooler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin-submissions',
  path: '/admin-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const R2048Route = R2048RouteImport.update({
  id: '/2048',
  path: '/2048',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/account': typeof AccountRoute
  '/admin-submissions': typeof AdminSubmissionsRoute
  '/admin-watercooler': typeof AdminWatercoolerRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/blog': typeof BlogRouteWithChildren
  '/bubbles': typeof BubblesRoute
  '/community-stories': typeof CommunityStoriesRoute
  '/match': typeof MatchRoute
  '/melody': typeof MelodyRoute
  '/my-breakroom': typeof MyBreakroomRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/shredder': typeof ShredderRoute
  '/smasher': typeof SmasherRoute
  '/snake': typeof SnakeRoute
  '/story-drafts': typeof StoryDraftsRoute
  '/submit-story': typeof SubmitStoryRoute
  '/vacation': typeof VacationRoute
  '/watercooler': typeof WatercoolerRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/account': typeof AccountRoute
  '/admin-submissions': typeof AdminSubmissionsRoute
  '/admin-watercooler': typeof AdminWatercoolerRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/blog': typeof BlogRouteWithChildren
  '/bubbles': typeof BubblesRoute
  '/community-stories': typeof CommunityStoriesRoute
  '/match': typeof MatchRoute
  '/melody': typeof MelodyRoute
  '/my-breakroom': typeof MyBreakroomRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/shredder': typeof ShredderRoute
  '/smasher': typeof SmasherRoute
  '/snake': typeof SnakeRoute
  '/story-drafts': typeof StoryDraftsRoute
  '/submit-story': typeof SubmitStoryRoute
  '/vacation': typeof VacationRoute
  '/watercooler': typeof WatercoolerRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/account': typeof AccountRoute
  '/admin-submissions': typeof AdminSubmissionsRoute
  '/admin-watercooler': typeof AdminWatercoolerRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/blog': typeof BlogRouteWithChildren
  '/bubbles': typeof BubblesRoute
  '/community-stories': typeof CommunityStoriesRoute
  '/match': typeof MatchRoute
  '/melody': typeof MelodyRoute
  '/my-breakroom': typeof MyBreakroomRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/shredder': typeof ShredderRoute
  '/smasher': typeof SmasherRoute
  '/snake': typeof SnakeRoute
  '/story-drafts': typeof StoryDraftsRoute
  '/submit-story': typeof SubmitStoryRoute
  '/vacation': typeof VacationRoute
  '/watercooler': typeof WatercoolerRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2048'
    | '/account'
    | '/admin-submissions'
    | '/admin-watercooler'
    | '/auth'
    | '/bingo'
    | '/blog'
    | '/bubbles'
    | '/community-stories'
    | '/match'
    | '/melody'
    | '/my-breakroom'
    | '/my-submissions'
    | '/onboarding'
    | '/shredder'
    | '/smasher'
    | '/snake'
    | '/story-drafts'
    | '/submit-story'
    | '/vacation'
    | '/watercooler'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2048'
    | '/account'
    | '/admin-submissions'
    | '/admin-watercooler'
    | '/auth'
    | '/bingo'
    | '/blog'
    | '/bubbles'
    | '/community-stories'
    | '/match'
    | '/melody'
    | '/my-breakroom'
    | '/my-submissions'
    | '/onboarding'
    | '/shredder'
    | '/smasher'
    | '/snake'
    | '/story-drafts'
    | '/submit-story'
    | '/vacation'
    | '/watercooler'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/2048'
    | '/account'
    | '/admin-submissions'
    | '/admin-watercooler'
    | '/auth'
    | '/bingo'
    | '/blog'
    | '/bubbles'
    | '/community-stories'
    | '/match'
    | '/melody'
    | '/my-breakroom'
    | '/my-submissions'
    | '/onboarding'
    | '/shredder'
    | '/smasher'
    | '/snake'
    | '/story-drafts'
    | '/submit-story'
    | '/vacation'
    | '/watercooler'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2048Route: typeof R2048Route
  AccountRoute: typeof AccountRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminWatercoolerRoute: typeof AdminWatercoolerRoute
  AuthRoute: typeof AuthRoute
  BingoRoute: typeof BingoRoute
  BlogRoute: typeof BlogRouteWithChildren
  BubblesRoute: typeof BubblesRoute
  CommunityStoriesRoute: typeof CommunityStoriesRoute
  MatchRoute: typeof MatchRoute
  MelodyRoute: typeof MelodyRoute
  MyBreakroomRoute: typeof MyBreakroomRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
  OnboardingRoute: typeof OnboardingRoute
  ShredderRoute: typeof ShredderRoute
  SmasherRoute: typeof SmasherRoute
  SnakeRoute: typeof SnakeRoute
  StoryDraftsRoute: typeof StoryDraftsRoute
  SubmitStoryRoute: typeof SubmitStoryRoute
  VacationRoute: typeof VacationRoute
  WatercoolerRoute: typeof WatercoolerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watercooler': {
      id: '/watercooler'
      path: '/watercooler'
      fullPath: '/watercooler'
      preLoaderRoute: typeof WatercoolerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacation': {
      id: '/vacation'
      path: '/vacation'
      fullPath: '/vacation'
      preLoaderRoute: typeof VacationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-story': {
      id: '/submit-story'
      path: '/submit-story'
      fullPath: '/submit-story'
      preLoaderRoute: typeof SubmitStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-drafts': {
      id: '/story-drafts'
      path: '/story-drafts'
      fullPath: '/story-drafts'
      preLoaderRoute: typeof StoryDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smasher': {
      id: '/smasher'
      path: '/smasher'
      fullPath: '/smasher'
      preLoaderRoute: typeof SmasherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shredder': {
      id: '/shredder'
      path: '/shredder'
      fullPath: '/shredder'
      preLoaderRoute: typeof ShredderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-breakroom': {
      id: '/my-breakroom'
      path: '/my-breakroom'
      fullPath: '/my-breakroom'
      preLoaderRoute: typeof MyBreakroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melody': {
      id: '/melody'
      path: '/melody'
      fullPath: '/melody'
      preLoaderRoute: typeof MelodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-stories': {
      id: '/community-stories'
      path: '/community-stories'
      fullPath: '/community-stories'
      preLoaderRoute: typeof CommunityStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bubbles': {
      id: '/bubbles'
      path: '/bubbles'
      fullPath: '/bubbles'
      preLoaderRoute: typeof BubblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-watercooler': {
      id: '/admin-watercooler'
      path: '/admin-watercooler'
      fullPath: '/admin-watercooler'
      preLoaderRoute: typeof AdminWatercoolerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-submissions': {
      id: '/admin-submissions'
      path: '/admin-submissions'
      fullPath: '/admin-submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2048': {
      id: '/2048'
      path: '/2048'
      fullPath: '/2048'
      preLoaderRoute: typeof R2048RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2048Route: R2048Route,
  AccountRoute: AccountRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminWatercoolerRoute: AdminWatercoolerRoute,
  AuthRoute: AuthRoute,
  BingoRoute: BingoRoute,
  BlogRoute: BlogRouteWithChildren,
  BubblesRoute: BubblesRoute,
  CommunityStoriesRoute: CommunityStoriesRoute,
  MatchRoute: MatchRoute,
  MelodyRoute: MelodyRoute,
  MyBreakroomRoute: MyBreakroomRoute,
  MySubmissionsRoute: MySubmissionsRoute,
  OnboardingRoute: OnboardingRoute,
  ShredderRoute: ShredderRoute,
  SmasherRoute: SmasherRoute,
  SnakeRoute: SnakeRoute,
  StoryDraftsRoute: StoryDraftsRoute,
  SubmitStoryRoute: SubmitStoryRoute,
  VacationRoute: VacationRoute,
  WatercoolerRoute: WatercoolerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
