/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchRouteImport } from './routes/match'
import { Route as BubblesRouteImport } from './routes/bubbles'
import { Route as R2048RouteImport } from './routes/2048'
import { Route as IndexRouteImport } from './routes/index'

const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const BubblesRoute = BubblesRouteImport.update({
  id: '/bubbles',
  path: '/bubbles',
  getParentRoute: () => rootRouteImport,
} as any)
const R2048Route = R2048RouteImport.update({
  id: '/2048',
  path: '/2048',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/bubbles': typeof BubblesRoute
  '/match': typeof MatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/bubbles': typeof BubblesRoute
  '/match': typeof MatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2048': typeof R2048Route
  '/bubbles': typeof BubblesRoute
  '/match': typeof MatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/2048' | '/bubbles' | '/match'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/2048' | '/bubbles' | '/match'
  id: '__root__' | '/' | '/2048' | '/bubbles' | '/match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2048Route: typeof R2048Route
  BubblesRoute: typeof BubblesRoute
  MatchRoute: typeof MatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bubbles': {
      id: '/bubbles'
      path: '/bubbles'
      fullPath: '/bubbles'
      preLoaderRoute: typeof BubblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2048': {
      id: '/2048'
      path: '/2048'
      fullPath: '/2048'
      preLoaderRoute: typeof R2048RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2048Route: R2048Route,
  BubblesRoute: BubblesRoute,
  MatchRoute: MatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
